on:
  push: # 每次 push 的时候触发

name: Build Release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # checkout 代码
      - uses: actions/setup-go@v2 # 配置 Go 环境
        with:
          go-version: "1.19.5" # 改成自己的版本
      - run: go test -v ./... # 测试代码
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # checkout 代码
      - uses: actions/setup-go@v2 # 配置 Go 环境
        with:
          go-version: "1.19.5" # 改成自己的版本
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    # 只有test完成时才会执行release
    needs: [ test, lint ]
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # checkout 代码
      - uses: actions/setup-go@v2 # 配置 Go 环境
        with:
          go-version: "1.19.5" # 改成自己的版本

      - run: go build -o chatgo_linux_amd64 main.go # 这 3 条是交叉编译 Go 的指令，酌情修改。
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o chatgo_darwin_amd64 main.go
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o chatgo_darwin_arm64 main.go

      # - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o chatgo_windows_amd64.exe ./...

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            chatgo_linux_amd64
            chatgo_darwin_amd64
            chatgo_darwin_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
